#FROM maven:3.6.3-openjdk-17 as build
#WORKDIR /usr/src/app
#COPY . .
#RUN mvn package -DskipTests

#FROM openjdk:17-slim
#RUN apt-get update && apt-get install -y netcat-openbsd
#COPY --from=build /usr/src/app/target/email-0.0.1-SNAPSHOT.jar /app/app.jar
#COPY --from=build /usr/src/app/wait-for-it.sh /app/wait-for-it.sh
#RUN chmod +x /app/wait-for-it.sh

#EXPOSE 8081
#CMD ["/app/wait-for-it.sh"]
