# Dockerfile para o API Gateway
#FROM openjdk:17-jdk-slim

#WORKDIR /app

# Copiar o arquivo JAR do gateway
#COPY target/gateway-0.0.1-SNAPSHOT.jar app.jar

# Expor a porta do gateway
#EXPOSE 8080

# Comando para executar a aplicação
#CMD ["java", "-jar", "app.jar"] 